# https://www.home-assistant.io/integrations/default_config/
default_config:

# Disable go2rtc - requires docker binary not available in dev environment
go2rtc:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.spaceapi_endpoint_client: debug
